/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.transkribus.native_interfaces;

public class Image {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Image(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Image obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        transkribus_interfacesJNI.delete_Image(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Image(String url) {
    this(transkribus_interfacesJNI.new_Image__SWIG_0(url), true);
  }

  public void doSthWithException() {
    transkribus_interfacesJNI.Image_doSthWithException(swigCPtr, this);
  }

  public Image(org.opencv.core.Mat mat) {
    this(transkribus_interfacesJNI.new_Image__SWIG_1(mat.getNativeObjAddr()), true);
  }

}
