/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.transkribus.native_interfaces;

public class IModuleDescription {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IModuleDescription(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IModuleDescription obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        transkribus_interfacesJNI.delete_IModuleDescription(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String usage() {
    return transkribus_interfacesJNI.IModuleDescription_usage(swigCPtr, this);
  }

  public String getToolName() {
    return transkribus_interfacesJNI.IModuleDescription_getToolName(swigCPtr, this);
  }

  public String getVersion() {
    return transkribus_interfacesJNI.IModuleDescription_getVersion(swigCPtr, this);
  }

  public String getProvider() {
    return transkribus_interfacesJNI.IModuleDescription_getProvider(swigCPtr, this);
  }

}
